// @generated by protobuf-ts 2.9.4 with parameter long_type_number
// @generated from protobuf file "sro/gamedata/gamedata.proto" (package "sro.gamedata", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { GameDataService } from "./gamedata";
/**
 * @generated from protobuf service sro.gamedata.GameDataService
 */
export interface IGameDataServiceClient {
}
/**
 * @generated from protobuf service sro.gamedata.GameDataService
 */
export class GameDataServiceClient implements IGameDataServiceClient, ServiceInfo {
    typeName = GameDataService.typeName;
    methods = GameDataService.methods;
    options = GameDataService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
}
