// @generated by protobuf-ts 2.9.4 with parameter long_type_number
// @generated from protobuf file "sro/gamedata/gamedata.proto" (package "sro.gamedata", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service sro.gamedata.GameDataService
 */
export const GameDataService = new ServiceType("sro.gamedata.GameDataService", []);
