// @generated by protobuf-ts 2.9.4 with parameter long_type_number
// @generated from protobuf file "sro/gameserver/data.proto" (package "sro.gameserver", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { GameServerDataService } from "./data";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GameServerDetails } from "./data";
import type { Empty } from "../../google/protobuf/empty";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service sro.gameserver.GameServerDataService
 */
export interface IGameServerDataServiceClient {
    /**
     * @generated from protobuf rpc: GetGameServerDetails(google.protobuf.Empty) returns (sro.gameserver.GameServerDetails);
     */
    getGameServerDetails(input: Empty, options?: RpcOptions): UnaryCall<Empty, GameServerDetails>;
}
/**
 * @generated from protobuf service sro.gameserver.GameServerDataService
 */
export class GameServerDataServiceClient implements IGameServerDataServiceClient, ServiceInfo {
    typeName = GameServerDataService.typeName;
    methods = GameServerDataService.methods;
    options = GameServerDataService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetGameServerDetails(google.protobuf.Empty) returns (sro.gameserver.GameServerDetails);
     */
    getGameServerDetails(input: Empty, options?: RpcOptions): UnaryCall<Empty, GameServerDetails> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GameServerDetails>("unary", this._transport, method, opt, input);
    }
}
