const DOMAIN = 'api.shatteredrealmsonline.com';

const ACCOUNTS_API_VERSION = 'v1';
const ACCOUNTS_API_BASE_URL = `https://${DOMAIN}/accounts`;
const ACCOUNTS_API_URL = `${ACCOUNTS_API_BASE_URL}/${ACCOUNTS_API_VERSION}`

const CHAT_API_VERSION = 'v1';
const CHAT_API_BASE_URL = `https://${DOMAIN}/chat`;
const CHAT_API_URL = `${CHAT_API_BASE_URL}/${CHAT_API_VERSION}`
const CHAT_GRPC_URL = `75.61.95.178`;

export const environment = {
  production: true,
  DOMAIN: DOMAIN,
  ACCOUNT_API_VERSION: ACCOUNTS_API_VERSION,
  ACCOUNT_API_BASE_URL: ACCOUNTS_API_BASE_URL,
  ACCOUNT_API_URL: ACCOUNTS_API_URL,
  CHAT_API_URL: CHAT_API_URL,
  CHAT_API_BASE_URL: CHAT_API_BASE_URL,
  CHAT_GRPC_URL: CHAT_GRPC_URL,
  recaptcha: {
    siteKey: '6LeFKkEhAAAAALeg05zJHu1kKaj-vSPdJ80ilEBV'
  },
};
